### ISSUE TITLE
External Libraries Check

### ISSUE THREAD

**Issue by VelinYordanov** [openhab/static-code-analysis#105]
Hello,

I am working on a check that verifies that all external libraries in a bundle (if they exist) are added properly:
The external libraries are packaged as a .jar file and usually located in a "lib" folder at the root of a bundle. The check should:

- assert that all jar files or the lib folder is added to the build.properties file;

- assert that all jar files are added to the "Bundle-Classpath:" MANIFEST.MF header.   
    
I have a few questions:
Is it mandatory for the folder to be named "lib"?
Could there be more than 1 folder, containing external dependencies?

@kaikreuzer  WDYT

**Comment by sjka** [comment]
> Is it mandatory for the folder to be named "lib"?

no

> Could there be more than 1 folder, containing external dependencies?

yes. So I think you will have to scan the entire folder tree inside the project for jar files. 

By the way, there can also be source-jars checked into the repository so that they can be used during development, but are intentionally not included in the bundle. Not sure if it is possible to distinguish them, but such a check would have to ignore them.

If that's possible, then this check certainly can't hurt. On the other hand: A bundle where the jars are not included in the packaging for sure will not work. And that's pretty unlikely to happen for someone who develops a binding in order to use his devices. I would assume people are not only trying them out, but really are using them at home...

**Comment by kaikreuzer** [comment]
>> Is it mandatory for the folder to be named "lib"?
> no

Well, according to our guidelines, yes: https://www.eclipse.org/smarthome/documentation/development/bindings/dependencies.html#3rd-party-libraries

I prefer if everyone follows the same conventions, so is there any good reason why people might want to use different or multiple folders here?

**Comment by VelinYordanov** [comment]
What severity should the check have?

> By the way, there can also be source-jars checked into the repository so that they can be used during development, but are intentionally not included in the bundle. Not sure if it is possible to distinguish them, but such a check would have to ignore them.

If the excluded jars are added to bin.excludes this will not be a problem.

**Comment by sjka** [comment]
Argh, I missed that point in the guidelines. Sorry for the confusion!

**Comment by VelinYordanov** [comment]
Very well. The check will assume there is only 1 folder named "lib" with external libraries.

**Comment by sjka** [comment]
With the dev guideline in mind: Shouldn't it be the other way round: the check scans for all JARs and will throw an error if it finds one outside the "lib" folder? Or is that what you meant?

**Comment by VelinYordanov** [comment]
The check asserts a lot of things, so I think it will be better to split the check in 4 smaller checks that assert:

- All external libraries from the lib folder are added to MANIFEST.MF

- All external libraries from the lib folder are added to build.properties

- All external libraries from the lib folder are added to .classpath

- There are no other external libraries in the bundle except the jars located in the lib folder

**Comment by VelinYordanov** [comment]
When i ran the checks in the openHAB 2 repository I found 2 bundles that have not added all of their jar files to the .classpath - org.openhab.voice.marytts and org.openhab.binding.zoneminder. Should i log an error for that or should it be a warning?

**Comment by kaikreuzer** [comment]
For marytts it is on purpose, as the jars are >20MB and there is no compile time dependency on them. For this reason, they are only downloaded at Maven build time and thus no .classpath entry exists as otherwise Eclipse would complain as the files seem to be missing. So a warning is ok here, but it should not be an error.

**Comment by kaikreuzer** [comment]
> All external libraries from the lib folder are added to .classpath

I would challenge this one. As seen, it does not apply for marrytts and checking https://github.com/openhab/openhab2-addons/issues/2461, it does not necessarily make sense for zoneminder either. So if @sjka agrees, I would remove this check. If a library is required on the classpath because source code depends on it, we will anyhow see compilation errors, if it is missing.

**Comment by VelinYordanov** [comment]
@sjka @kaikreuzer The pull request is ready. Can you take a look?
