### ISSUE TITLE
A generic method return value.

### ISSUE THREAD

**Issue by doandzhi** [openhab/static-code-analysis#153]
The generic method **findLineNumber()** returns -1 when a word isn't found in the source file and @martinvw  proposed returning _exception_ in a code review of mine [here](https://github.com/openhab/static-code-analysis/pull/139#discussion_r134029675). 

Can I have your opinion @svilenvul ?

**Comment by svilenvul** [comment]
Thanks, I agree, It is definitely a good idea.

**Comment by svilenvul** [comment]
@martinvw, this method has caused some problems, because it is not forcing the developers to handle the case and that leads to some unexpected exceptions (we already experienced that in previous releases). So we should throw some custom *checked* exception ?

On the other hand this is *not an exceptional case* - you search in lines of text and the text that you search is simply not there (or you are searching a multi line text).  This method is very similar to `String.indexOf()` methods, that are also returning "-1".

**Comment by martinvw** [comment]
I think that given the limited scope in which we used it combined with the facts that we missed handling it in the past definitely justifies a checked exception. 

There are core methods which have similar behavior although not all people like it in that specific method: [From JPA `Query.getSingleResult()`](http://docs.oracle.com/javaee/7/api/javax/persistence/Query.html#getSingleResult--)
