### ISSUE TITLE
RequireBundleCheck

### ISSUE THREAD

**Issue by petarnv** [openhab/static-code-analysis#16]
I have started implementing a check that verifies if the MANIFEST.MF file contains a `Require-Bundle` header.

**Comment by petarnv** [comment]
A PR is now opened: https://github.com/openhab/static-code-analysis/pull/19.

**Comment by martinvw** [comment]
@petarnv I think this one is resolved now, since the PR is merged.

**Comment by svilenvul** [comment]
Thanks @martinvw

**Comment by svilenvul** [comment]
@kaikreuzer, @sjka

Could we make this check a bit less strict ?

The reason is that a lot of test bundles are using a `Require-Bundle` header for `org.mockito` (and some for `org.junit` and `org.hamcrest`). 

We have here two approaches - disable the check for all test bundles or add a few bundles as exceptions (as these above).

Of course if it is possible, we could remove the `Require-Bundle` entries at all.

Please let me know what do you think ?

**Comment by kaikreuzer** [comment]
> disable the check for all test bundles

I thought we had already agreed on that a while ago. For test bundles/fragments, we indeed do not need to enforce this check.

**Comment by svilenvul** [comment]
Thanks, maybe I forgot about it :)

**Comment by kaikreuzer** [comment]
... or I dreamt about it ;-)
