### ISSUE TITLE
Enrich the AuthorTagCheck with "Initial contribution" Check for the First Author

### ISSUE THREAD

**Issue by dstivanov** [openhab/static-code-analysis#199]
Usually, the first mentioned author in the Java file has done the Initial contribution. Can we enrich the AuthorTagCheck in order to check whether the "Initial contribution" is present as the description of the contribution of the first author in the list? 

However, as the severity of the AuthorTagCheck is ERROR we can think of another check,  that will produce WARNING, if 

- There is no description for some of the authors
- There is not "Initial contribution" for the first author.

**Comment by martinvw** [comment]
Maybe we should define an order as well i believe it varies?

**Comment by dstivanov** [comment]
I don't know whether we need specific ordering of the authors' contributions (for  example by the date of contribution, ascending or descending). So in my opinion it will be enough to check that each file has at least one author with "Initial contribution"  contribution description and all the other authors can have random contribution description (but not empty).

**Comment by kssimova** [comment]
I'm currently working on this issue and I have few questions, as I am not sure how exactly should the check work: 

- For example, should it be OK if first author has “Initial contribution and API” contribution description or should we produce WARNING, because it is not exactly “Initial contribution”? 

- Should we include “Initial implementation” as possible contribution description of the first author, as I have seen it several times in several classes? 

@kaikreuzer

**Comment by davidgraeff** [comment]
Actually this redundancy with contribution descriptions is not very useful at all (there is git blame). The descriptions are never accurate, don't follow any rules (not machine readable) and are of no use. If I want to contact an author regarding a question, I need to use git blame anyway, to retrieve the email address, as we do not add those to the files.

Long story short: The authors should be mandatory, the order of the authors should be meaningful, the description should be optional.

**Comment by kaikreuzer** [comment]
Sorry for not having responded @kssimova, I didn't see your ping at the time.

I have to admit that what @davidgraeff says is what our official current guideline is (point A.4 on https://www.eclipse.org/smarthome/documentation/development/guidelines.html#a-code-style).

Nonetheless, we follow the [Eclipse guidelines](https://www.eclipse.org/projects/handbook/#ip-copyright-headers), which state as (4): "The names of the contributors and the nature of their contribution"

As Java code is anyhow redundant at many places, I do think that adding a word on the "nature f their contribution" isn't a bad thing and we indeed enforced "Initial contribution and API" for the first author when doing reviews. Having this in place imho prevents that the order of the author tags is silently changed.

I'd therefore say it is ok to do a warning if this exact phrase isn't present - it simply ensures that our code is homogenous and it doesn't really cost any effort to anyone.
But of course the other ESH core maintainers (@sjka, @maggu2810) have a say here, too.

**Comment by maggu2810** [comment]
Personally I don't care about the `@author` lines in the file and prefer `git blame`, too.

@kaikreuzer If I understand the Eclipse guidelines correctly there are two options:

> Copyright headers can take one of two forms. In the traditional form

> In the traditional form
> The names of the contributors and the nature of their contribution (this section may be excluded).

So, in the traditional form the authors have to be part of the license header in the file (see example on the resp. guidelines page).

> Alternatively, project teams can adopt a more generic copyright header for each file and include the identities of the copyright holders in the notice file.

Here the "identities" (in my reading the contributors) have to be placed in the notice file.

From my understanding there is no option to add this information to the VCS only.
We have choosen the file header instead of placing the information to the separate notice file.

So, if my understanding of the Eclipse guidelines have been correct, I don't think it costs any real effort to use as first entry the specific one (to be homogeneous).

**Comment by kaikreuzer** [comment]
@maggu2810 So if I understand you right, you also vote for adding this check for the sake of homogeneity - @dstivanov let's go for it then!

**Comment by kssimova** [comment]
@kaikreuzer So, should we check only the contribution description of the first present javadoc author and not check the others? What about the description - should we use only "Initial contribution" and not "Initial implementation"?

**Comment by kaikreuzer** [comment]
@kssimova You can check the presence of a description for all authors and the first one to start with "Initial contribution" (as "Initial contribution and API" is also common and equally ok, I would say).

**Comment by maggu2810** [comment]
@kaikreuzer Sorry, I don't know how you manage it but I don't manage it yet to read the hundreds of mails per day. Please ping me on IM, mail or similar :wink:
