### ISSUE TITLE
Check that parametrized logging is used

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#20]
A common mistake is to [use string concatenation](https://github.com/openhab/static-code-analysis/pull/19#discussion_r106190665) instead of parametrized logging in slf4j.
Would be great if there could be a check for that!

**Comment by svilenvul** [comment]
Thanks to Markus Rathgeb we have the [findbugs-slf4j](https://github.com/KengoTODA/findbugs-slf4j) plugin added to the tool and it provides a check for this mistake - https://github.com/KengoTODA/findbugs-slf4j#slf4j_format_should_be_const.

We have not activated it because it will fail the build - the bug detector logs this bug as [high priority](https://github.com/KengoTODA/findbugs-slf4j/blob/473bfddacbc3d2b3a4f1f8ff7d10cc6902e5d3da/bug-pattern/src/main/java/jp/skypencil/findbugs/slf4j/parameter/AbstractDetectorForParameterArray.java#L170). We have still not found a way to avoid failing the build while still logging the issue. ..

**Comment by kaikreuzer** [comment]
> We have not activated it because it will fail the build

You mean also failing even if failOnError=false?
If you are only concerned about the "high priority", I think this is fully correct; if I see such a mistake in the code, I also always ask it to be changed - so it is ok for me, if it would not pass the checks.

Did you check, how many problems there currently are in the code base? Would it be possible to fix them?

**Comment by svilenvul** [comment]
> You mean also failing even if failOnError=false?

No, only with the failOnError=true, the default that we use.

> Did you check, how many problems there currently are in the code base? 

No, the build just failed at the beginning.

> Would it be possible to fix them?

Yes I will give it a try :)

> If you are only concerned about the "high priority", I think this is fully correct

Yes, this was my concern. I will add the check than after fixing the issues.
