### ISSUE TITLE
Standardize line endings using checks or .gitattributes

### ISSUE THREAD

**Issue by wborn** [openhab/static-code-analysis#273]
Currently the code bases contains a mix of both Unix and Windows line endings.

There are several ways to standardize the line endings being used:
* It can be done by adding .gitattributes files in your repo so they are converted automatically. See also the [documentation](https://git-scm.com/docs/gitattributes) and some commonly used [templates](https://github.com/alexkaratarakis/gitattributes).
* We could also add checks for it in SAT.

On the command line you can find files with Windows line endings with find using:
```
find . -not -type d -not \( -path "*target/*" -prune \) -not \( -path "*.git/*" -prune \) -not \( -path "*.settings/*" -prune \) -not \( -path "*/node_modules/*" -prune \) -not \( -path "*.cmd" -prune \) -exec file "{}" ";" | grep CRLF
```

**Comment by svilenvul** [comment]
Similar discussion: https://github.com/checkstyle/checkstyle/issues/893

It was hard for me to follow, if the check is already has been implemented. It is definitely worth the effort  to search for existing implementation first, before we decide to implement a new check.

**Comment by kaikreuzer** [comment]
Adding a check is imho not a solution as it will merely annoy Windows users, who would then wonder what they should do in order to change the line endings (which isn't necessarily trivial to figure out, if you are a Windows user).

We should therefore analyse whether we can add a .gitattributes to the repo and whether this correctly addresses the problem. If so, it will probably only address it, once files are committed to the repo, so a SAT check would actually be counter-productive (as it would blame the user for a problem, which would go away, once the code is comitted).

**Comment by svilenvul** [comment]
As no check is expected (at least the opened PR is closed), I will close the issue.

Please continue the discussion if needed in individual repositories, where the .gitattributes would be eventually added.
