### ISSUE TITLE
pom first approach

### ISSUE THREAD

**Issue by maggu2810** [openhab/static-code-analysis#341]
On Eclipse SmartHome the tool has been enabled if there is a `META-INF/MANIFEST.MF` file present.
See: https://github.com/eclipse/smarthome/blob/f2a1f38/pom.xml#L591

As such files does not exist on a pom first approach (e.g. Maven + Bnd), I wonder if the static-code-analysis is working for such projects.
I assume your tests depends on the manifest file that is "hard coded" and present in front of the generation in front of the package phase.

Can you give me some insides and if it is not working if you plan to add support?

**Comment by wborn** [comment]
Perhaps the `MANIFEST.MF` location can be made configurable?
It's still generated as `target/classes/META-INF/MANIFEST.MF`

**Comment by splatch** [comment]
Its quite good question if we/you should apply any checks on generated resource. Previously it was maintained manually so at least from maintenance point of view it was important to keep proper order of imports, exports etc.
Do we care about that when we generate this metadata?

**Comment by wborn** [comment]
I think you can still add the wrong content to `bnd.bnd` files which may introduce SAT issues even though the manifest is generated. @maggu2810 also [commented](https://github.com/martinvw/openhab-webui/pull/1#issuecomment-468314423) that in the future annotations may be used instead of a `bnd.bnd` file. So it might not be useful to write new SAT code for validating the `bnd.bnd` file content.

**Comment by splatch** [comment]
Fair enough, then its easier to verify output than follow bnd macro language.
